### ISSUE TITLE
SEFLG_SWIEPH and SEFLG_SPEED as default flags

### ISSUE THREAD

**Issue by dwlnetnl** [astrorigin/pyswisseph#7]
I noticed that always SEFLG_SWIEPH and where appropriate SEFLG_SPEED is used as default flags. This alters the default behavior of the SwissEph in a way users may get confused because it isn't as the manual specifies the library should work.

Do you mind changing this behavior?

**Comment by astrorigin** [comment]
From file swephexp.h line 172:

 * The flag bits are defined in such a way that iflag = 0 delivers what one
 * usually wants:
 *    - the default ephemeris (SWISS EPHEMERIS) is used,
 *    - apparent geocentric positions referring to the true equinox of date
 *      are returned.
 * If not only coordinates, but also speed values are required, use 
 * flag = SEFLG_SPEED.

So SEFLG_SWIEPH should be the default.
Concerning SEFLG_SPEED, most modern astrologers (in my experience) would want to check speed out in order to get if the object is retrograde (or direct).
