### ISSUE TITLE
"swisseph.Error: swisseph.houses: error" error in a specific example

### ISSUE THREAD

**Issue by Graily** [astrorigin/pyswisseph#74]
I found a specific example when calculating the ascendant.

i'm using: cusps, houses = swe.houses(jul_day_ut, lat, long, b'P') and it works for 99.9% of time but, with
julian_date = 2449477.829861111  
latitude = 67.5035662  
longitude = 64.0627028

I get an error: "swisseph.Error: swisseph.houses: error". 

Tweaking latitude a little bit, i found out that on 66.5 and less - it works fine, but on 66.5+ - not.

**Comment by astrorigin** [comment]
"The Placidus house system in astrology does not work above 66.5° of latitude because it relies on the division of the celestial sphere based on time (the diurnal arc), which becomes problematic at these high latitudes. Above 66.5°, the sun can remain above or below the horizon for 24 hours during certain times of the year, making it impossible to accurately divide the houses based on the traditional time-based method used in the Placidus system."

The original Swisseph library (in C) has chosen to handle the case like this:

"Placidus and Koch house cusps as well as Gauquelin sectors cannot be computed beyond the polar circle. In such cases, swe_houses() switches to Porphyry houses (each quadrant is divided into three equal parts) and returns the error code ERR."

The Pyswisseph has deliberately chosen to raise an exception instead. You should either detect the error before the call to swe.houses or let the exception happen and then provide an alternative method of your choice. It is more strict, but every astrology student should stumble upon that problem once in his/her life, and give it a thought.


In the next version, we will make the error message more informative, and update our documentation.

**Comment by Graily** [comment]
is there any other way to calculate ascendant for 66.5+ latutudes? there is quite a lot of towns over 66.5 degrees and i probably need to use then very often. but dont really need all houses.

**Comment by aum7** [comment]
you can try using 

```
# houses flags : 0 or FLG_SIDEREAL or FLG_RADIANS or FLG_NONUT
# houses_ex returns : cusps (12) & ascmc (8) : 0 asc | 1 mc | 2 armc |
# 3 vertex | 4 equatorial asc | 5 co-asc (koch) | 6 co-asc (munkasey) |
# 7 polar asc (munkasey)
# vertex = point on ecliptic, located in precise western direction
houses, ascmc = swe.houses_ex(jd_ut_1, lat_1, lon_1, house_byte, flags)
...
asc = ascmc[0]
```
have fun
aum
